version: "3"
services:
  bigquery_python:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: bigquery_python-image
    container_name: bigquery_python-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
